version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: banking_postgres
    ports:
      - "4321:5432"
    environment:
      POSTGRES_USER: ht
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: banking_app
    volumes:
      - sample_banking_pg_data:/var/lib/postgresql/data
    restart: on-failure

  
  rabbitmq:
    image: rabbitmq:3.6.6-management-alpine
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672


volumes:
  sample_banking_pg_data:
