version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: banking_postgres
    ports:
      - "4321:5432"
    environment:
      POSTGRES_USER: ht
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: banking_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
